// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template.proto

package com.ava.frame.netty.proto;

public final class Template {
  private Template() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ava.frame.netty.proto.ReqChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.ava.frame.netty.proto.ReqChat}
   */
  public  static final class ReqChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ava.frame.netty.proto.ReqChat)
      ReqChatOrBuilder {
    // Use ReqChat.newBuilder() to construct.
    private ReqChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqChat() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Template.internal_static_com_ava_frame_netty_proto_ReqChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Template.internal_static_com_ava_frame_netty_proto_ReqChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReqChat.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReqChat)) {
        return super.equals(obj);
      }
      ReqChat other = (ReqChat) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReqChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReqChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReqChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ava.frame.netty.proto.ReqChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ava.frame.netty.proto.ReqChat)
        ReqChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Template.internal_static_com_ava_frame_netty_proto_ReqChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Template.internal_static_com_ava_frame_netty_proto_ReqChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReqChat.class, Builder.class);
      }

      // Construct using com.ava.frame.netty.proto.Template.ReqChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Template.internal_static_com_ava_frame_netty_proto_ReqChat_descriptor;
      }

      public ReqChat getDefaultInstanceForType() {
        return ReqChat.getDefaultInstance();
      }

      public ReqChat build() {
        ReqChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReqChat buildPartial() {
        ReqChat result = new ReqChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReqChat) {
          return mergeFrom((ReqChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReqChat other) {
        if (other == ReqChat.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReqChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReqChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ava.frame.netty.proto.ReqChat)
    }

    // @@protoc_insertion_point(class_scope:com.ava.frame.netty.proto.ReqChat)
    private static final ReqChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReqChat();
    }

    public static ReqChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ReqChat>
        PARSER = new com.google.protobuf.AbstractParser<ReqChat>() {
      public ReqChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqChat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReqChat> getParserForType() {
      return PARSER;
    }

    public ReqChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RespChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ava.frame.netty.proto.RespChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sign = 1;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 1;</code>
     */
    String getSign();
    /**
     * <code>required string sign = 1;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();
  }
  /**
   * Protobuf type {@code com.ava.frame.netty.proto.RespChat}
   */
  public  static final class RespChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ava.frame.netty.proto.RespChat)
      RespChatOrBuilder {
    // Use RespChat.newBuilder() to construct.
    private RespChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RespChat() {
      sign_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RespChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sign_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Template.internal_static_com_ava_frame_netty_proto_RespChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Template.internal_static_com_ava_frame_netty_proto_RespChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RespChat.class, Builder.class);
    }

    private int bitField0_;
    public static final int SIGN_FIELD_NUMBER = 1;
    private volatile Object sign_;
    /**
     * <code>required string sign = 1;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sign = 1;</code>
     */
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sign_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sign_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RespChat)) {
        return super.equals(obj);
      }
      RespChat other = (RespChat) obj;

      boolean result = true;
      result = result && (hasSign() == other.hasSign());
      if (hasSign()) {
        result = result && getSign()
            .equals(other.getSign());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSign()) {
        hash = (37 * hash) + SIGN_FIELD_NUMBER;
        hash = (53 * hash) + getSign().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RespChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RespChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RespChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RespChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RespChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RespChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RespChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ava.frame.netty.proto.RespChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ava.frame.netty.proto.RespChat)
        RespChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Template.internal_static_com_ava_frame_netty_proto_RespChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Template.internal_static_com_ava_frame_netty_proto_RespChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RespChat.class, Builder.class);
      }

      // Construct using com.ava.frame.netty.proto.Template.RespChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Template.internal_static_com_ava_frame_netty_proto_RespChat_descriptor;
      }

      public RespChat getDefaultInstanceForType() {
        return RespChat.getDefaultInstance();
      }

      public RespChat build() {
        RespChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RespChat buildPartial() {
        RespChat result = new RespChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sign_ = sign_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RespChat) {
          return mergeFrom((RespChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RespChat other) {
        if (other == RespChat.getDefaultInstance()) return this;
        if (other.hasSign()) {
          bitField0_ |= 0x00000001;
          sign_ = other.sign_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSign()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RespChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RespChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object sign_ = "";
      /**
       * <code>required string sign = 1;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sign_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder setSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 1;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sign_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ava.frame.netty.proto.RespChat)
    }

    // @@protoc_insertion_point(class_scope:com.ava.frame.netty.proto.RespChat)
    private static final RespChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RespChat();
    }

    public static RespChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<RespChat>
        PARSER = new com.google.protobuf.AbstractParser<RespChat>() {
      public RespChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RespChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RespChat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RespChat> getParserForType() {
      return PARSER;
    }

    public RespChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ava.frame.netty.proto.MessageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string service = 1;</code>
     */
    boolean hasService();
    /**
     * <code>required string service = 1;</code>
     */
    String getService();
    /**
     * <code>required string service = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    /**
     * <code>required int32 sn = 2;</code>
     */
    boolean hasSn();
    /**
     * <code>required int32 sn = 2;</code>
     */
    int getSn();

    /**
     * <code>optional string token = 3;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 3;</code>
     */
    String getToken();
    /**
     * <code>optional string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional int32 uid = 4;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 4;</code>
     */
    int getUid();

    /**
     * <code>optional int32 code = 5;</code>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 5;</code>
     */
    int getCode();

    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    boolean hasMsg();
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    String getMsg();
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    boolean hasReqChat();
    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    ReqChat getReqChat();
    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    ReqChatOrBuilder getReqChatOrBuilder();

    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    boolean hasRespChat();
    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    RespChat getRespChat();
    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    RespChatOrBuilder getRespChatOrBuilder();
  }
  /**
   * <pre>
   *响应&amp;请求 只允许新增
   * </pre>
   *
   * Protobuf type {@code com.ava.frame.netty.proto.MessageInfo}
   */
  public  static final class MessageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ava.frame.netty.proto.MessageInfo)
      MessageInfoOrBuilder {
    // Use MessageInfo.newBuilder() to construct.
    private MessageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageInfo() {
      service_ = "";
      sn_ = 0;
      token_ = "";
      uid_ = 0;
      code_ = 0;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              service_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sn_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              token_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              uid_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              code_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msg_ = bs;
              break;
            }
            case 58: {
              ReqChat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = reqChat_.toBuilder();
              }
              reqChat_ = input.readMessage(ReqChat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reqChat_);
                reqChat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              RespChat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = respChat_.toBuilder();
              }
              respChat_ = input.readMessage(RespChat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(respChat_);
                respChat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Template.internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Template.internal_static_com_ava_frame_netty_proto_MessageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageInfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int SERVICE_FIELD_NUMBER = 1;
    private volatile Object service_;
    /**
     * <code>required string service = 1;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string service = 1;</code>
     */
    public String getService() {
      Object ref = service_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          service_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SN_FIELD_NUMBER = 2;
    private int sn_;
    /**
     * <code>required int32 sn = 2;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sn = 2;</code>
     */
    public int getSn() {
      return sn_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile Object token_;
    /**
     * <code>optional string token = 3;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 4;
    private int uid_;
    /**
     * <code>optional int32 uid = 4;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 uid = 4;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private int code_;
    /**
     * <code>optional int32 code = 5;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 code = 5;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 6;
    private volatile Object msg_;
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>optional string msg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQCHAT_FIELD_NUMBER = 7;
    private ReqChat reqChat_;
    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    public boolean hasReqChat() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    public ReqChat getReqChat() {
      return reqChat_ == null ? ReqChat.getDefaultInstance() : reqChat_;
    }
    /**
     * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
     */
    public ReqChatOrBuilder getReqChatOrBuilder() {
      return reqChat_ == null ? ReqChat.getDefaultInstance() : reqChat_;
    }

    public static final int RESPCHAT_FIELD_NUMBER = 8;
    private RespChat respChat_;
    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    public boolean hasRespChat() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    public RespChat getRespChat() {
      return respChat_ == null ? RespChat.getDefaultInstance() : respChat_;
    }
    /**
     * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
     */
    public RespChatOrBuilder getRespChatOrBuilder() {
      return respChat_ == null ? RespChat.getDefaultInstance() : respChat_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasReqChat()) {
        if (!getReqChat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRespChat()) {
        if (!getRespChat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, uid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, code_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msg_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, getReqChat());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, getRespChat());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, uid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, code_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msg_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getReqChat());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getRespChat());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageInfo)) {
        return super.equals(obj);
      }
      MessageInfo other = (MessageInfo) obj;

      boolean result = true;
      result = result && (hasService() == other.hasService());
      if (hasService()) {
        result = result && getService()
            .equals(other.getService());
      }
      result = result && (hasSn() == other.hasSn());
      if (hasSn()) {
        result = result && (getSn()
            == other.getSn());
      }
      result = result && (hasToken() == other.hasToken());
      if (hasToken()) {
        result = result && getToken()
            .equals(other.getToken());
      }
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && (getUid()
            == other.getUid());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && (hasReqChat() == other.hasReqChat());
      if (hasReqChat()) {
        result = result && getReqChat()
            .equals(other.getReqChat());
      }
      result = result && (hasRespChat() == other.hasRespChat());
      if (hasRespChat()) {
        result = result && getRespChat()
            .equals(other.getRespChat());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasService()) {
        hash = (37 * hash) + SERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getService().hashCode();
      }
      if (hasSn()) {
        hash = (37 * hash) + SN_FIELD_NUMBER;
        hash = (53 * hash) + getSn();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasReqChat()) {
        hash = (37 * hash) + REQCHAT_FIELD_NUMBER;
        hash = (53 * hash) + getReqChat().hashCode();
      }
      if (hasRespChat()) {
        hash = (37 * hash) + RESPCHAT_FIELD_NUMBER;
        hash = (53 * hash) + getRespChat().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应&amp;请求 只允许新增
     * </pre>
     *
     * Protobuf type {@code com.ava.frame.netty.proto.MessageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ava.frame.netty.proto.MessageInfo)
        MessageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Template.internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Template.internal_static_com_ava_frame_netty_proto_MessageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageInfo.class, Builder.class);
      }

      // Construct using com.ava.frame.netty.proto.Template.MessageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReqChatFieldBuilder();
          getRespChatFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        service_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (reqChatBuilder_ == null) {
          reqChat_ = null;
        } else {
          reqChatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (respChatBuilder_ == null) {
          respChat_ = null;
        } else {
          respChatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Template.internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor;
      }

      public MessageInfo getDefaultInstanceForType() {
        return MessageInfo.getDefaultInstance();
      }

      public MessageInfo build() {
        MessageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageInfo buildPartial() {
        MessageInfo result = new MessageInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (reqChatBuilder_ == null) {
          result.reqChat_ = reqChat_;
        } else {
          result.reqChat_ = reqChatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (respChatBuilder_ == null) {
          result.respChat_ = respChat_;
        } else {
          result.respChat_ = respChatBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageInfo) {
          return mergeFrom((MessageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageInfo other) {
        if (other == MessageInfo.getDefaultInstance()) return this;
        if (other.hasService()) {
          bitField0_ |= 0x00000001;
          service_ = other.service_;
          onChanged();
        }
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000004;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000020;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasReqChat()) {
          mergeReqChat(other.getReqChat());
        }
        if (other.hasRespChat()) {
          mergeRespChat(other.getRespChat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasService()) {
          return false;
        }
        if (!hasSn()) {
          return false;
        }
        if (hasReqChat()) {
          if (!getReqChat().isInitialized()) {
            return false;
          }
        }
        if (hasRespChat()) {
          if (!getRespChat().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object service_ = "";
      /**
       * <code>required string service = 1;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string service = 1;</code>
       */
      public String getService() {
        Object ref = service_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            service_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string service = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service = 1;</code>
       */
      public Builder setService(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service = 1;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000001);
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>required string service = 1;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        service_ = value;
        onChanged();
        return this;
      }

      private int sn_ ;
      /**
       * <code>required int32 sn = 2;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>optional string token = 3;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 4;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 uid = 4;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 4;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000008;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 4;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uid_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 5;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000010;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>optional string msg = 6;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msg_ = value;
        onChanged();
        return this;
      }

      private ReqChat reqChat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ReqChat, ReqChat.Builder, ReqChatOrBuilder> reqChatBuilder_;
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public boolean hasReqChat() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public ReqChat getReqChat() {
        if (reqChatBuilder_ == null) {
          return reqChat_ == null ? ReqChat.getDefaultInstance() : reqChat_;
        } else {
          return reqChatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public Builder setReqChat(ReqChat value) {
        if (reqChatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reqChat_ = value;
          onChanged();
        } else {
          reqChatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public Builder setReqChat(
          ReqChat.Builder builderForValue) {
        if (reqChatBuilder_ == null) {
          reqChat_ = builderForValue.build();
          onChanged();
        } else {
          reqChatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public Builder mergeReqChat(ReqChat value) {
        if (reqChatBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              reqChat_ != null &&
              reqChat_ != ReqChat.getDefaultInstance()) {
            reqChat_ =
              ReqChat.newBuilder(reqChat_).mergeFrom(value).buildPartial();
          } else {
            reqChat_ = value;
          }
          onChanged();
        } else {
          reqChatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public Builder clearReqChat() {
        if (reqChatBuilder_ == null) {
          reqChat_ = null;
          onChanged();
        } else {
          reqChatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public ReqChat.Builder getReqChatBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getReqChatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      public ReqChatOrBuilder getReqChatOrBuilder() {
        if (reqChatBuilder_ != null) {
          return reqChatBuilder_.getMessageOrBuilder();
        } else {
          return reqChat_ == null ?
              ReqChat.getDefaultInstance() : reqChat_;
        }
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.ReqChat reqChat = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ReqChat, ReqChat.Builder, ReqChatOrBuilder>
          getReqChatFieldBuilder() {
        if (reqChatBuilder_ == null) {
          reqChatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ReqChat, ReqChat.Builder, ReqChatOrBuilder>(
                  getReqChat(),
                  getParentForChildren(),
                  isClean());
          reqChat_ = null;
        }
        return reqChatBuilder_;
      }

      private RespChat respChat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          RespChat, RespChat.Builder, RespChatOrBuilder> respChatBuilder_;
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public boolean hasRespChat() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public RespChat getRespChat() {
        if (respChatBuilder_ == null) {
          return respChat_ == null ? RespChat.getDefaultInstance() : respChat_;
        } else {
          return respChatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public Builder setRespChat(RespChat value) {
        if (respChatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          respChat_ = value;
          onChanged();
        } else {
          respChatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public Builder setRespChat(
          RespChat.Builder builderForValue) {
        if (respChatBuilder_ == null) {
          respChat_ = builderForValue.build();
          onChanged();
        } else {
          respChatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public Builder mergeRespChat(RespChat value) {
        if (respChatBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              respChat_ != null &&
              respChat_ != RespChat.getDefaultInstance()) {
            respChat_ =
              RespChat.newBuilder(respChat_).mergeFrom(value).buildPartial();
          } else {
            respChat_ = value;
          }
          onChanged();
        } else {
          respChatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public Builder clearRespChat() {
        if (respChatBuilder_ == null) {
          respChat_ = null;
          onChanged();
        } else {
          respChatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public RespChat.Builder getRespChatBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getRespChatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      public RespChatOrBuilder getRespChatOrBuilder() {
        if (respChatBuilder_ != null) {
          return respChatBuilder_.getMessageOrBuilder();
        } else {
          return respChat_ == null ?
              RespChat.getDefaultInstance() : respChat_;
        }
      }
      /**
       * <code>optional .com.ava.frame.netty.proto.RespChat respChat = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RespChat, RespChat.Builder, RespChatOrBuilder>
          getRespChatFieldBuilder() {
        if (respChatBuilder_ == null) {
          respChatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RespChat, RespChat.Builder, RespChatOrBuilder>(
                  getRespChat(),
                  getParentForChildren(),
                  isClean());
          respChat_ = null;
        }
        return respChatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ava.frame.netty.proto.MessageInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ava.frame.netty.proto.MessageInfo)
    private static final MessageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageInfo();
    }

    public static MessageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MessageInfo>
        PARSER = new com.google.protobuf.AbstractParser<MessageInfo>() {
      public MessageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageInfo> getParserForType() {
      return PARSER;
    }

    public MessageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ava_frame_netty_proto_ReqChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ava_frame_netty_proto_ReqChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ava_frame_netty_proto_RespChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ava_frame_netty_proto_RespChat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ava_frame_netty_proto_MessageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016template.proto\022\031com.ava.frame.netty.pr" +
      "oto\"\027\n\007ReqChat\022\014\n\004name\030\001 \002(\t\"\030\n\010RespChat" +
      "\022\014\n\004sign\030\001 \002(\t\"\315\001\n\013MessageInfo\022\017\n\007servic" +
      "e\030\001 \002(\t\022\n\n\002sn\030\002 \002(\005\022\r\n\005token\030\003 \001(\t\022\013\n\003ui" +
      "d\030\004 \001(\005\022\014\n\004code\030\005 \001(\005\022\013\n\003msg\030\006 \001(\t\0223\n\007re" +
      "qChat\030\007 \001(\0132\".com.ava.frame.netty.proto." +
      "ReqChat\0225\n\010respChat\030\010 \001(\0132#.com.ava.fram" +
      "e.netty.proto.RespChatB%\n\031com.ava.frame." +
      "netty.protoB\010Template"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ava_frame_netty_proto_ReqChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ava_frame_netty_proto_ReqChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ava_frame_netty_proto_ReqChat_descriptor,
        new String[] { "Name", });
    internal_static_com_ava_frame_netty_proto_RespChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ava_frame_netty_proto_RespChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ava_frame_netty_proto_RespChat_descriptor,
        new String[] { "Sign", });
    internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ava_frame_netty_proto_MessageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ava_frame_netty_proto_MessageInfo_descriptor,
        new String[] { "Service", "Sn", "Token", "Uid", "Code", "Msg", "ReqChat", "RespChat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
